[workspace]
members = [
    "engine/board",
    "engine/brain",
    "engine/core",
    "event-stream",
    "lambda/benchmark",
    "lambda/chessgame",
    "lambda/chessmove",
    "lambda/challenge",
    "lib/payloads",
    "openings/dynamodb-uploader",
    "openings/pgn-extractor",
    "lib/response-stream",
]
exclude = [
    "uci-client"
]