[package]
name = "pgn-extractor"
version = "0.1.0"
authors = ["Thomas Ball <tomoliverball@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.21"
dotenv = "0.15.0"
regex = "1"
lazy_static = "1.2.0"
itertools = "0.8.2"
myopic-board = "2.1.3"
serde_derive = "1.0.115"
serde = "1.0.115"
serde_json = "1.0.59"
serde_with = "1.6.0"
indicatif = "0.15.0"
chrono = "0.4"
anyhow = "1.0.37"
