[package]
name = "pgn-extractor"
version = "0.0.0"
authors = ["Thomas Ball <tomoliverball@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyperopic = { path = "../../engine/hyperopic" }
structopt = "0.3.26"
regex = "1.8.1"
lazy_static = "1.4.0"
itertools = "0.10.5"
serde_derive = "1.0.163"
serde = "1.0.163"
serde_json = "1.0.96"
indicatif = "0.17.3"
chrono = "0.4.24"
anyhow = "1.0.71"
